claim:
  cost: 25000
  info-display:
    - "Owner: %owner"
    - "Members: %members"
    - "Trustees: %trustees"
    - "Size: %size"
  particleType: "villager_happy"

message:
  chunkClaimSuccess: "Claim successful."
  chunkClaimFailureMoney: "You need %d to make a claim."
  chunkClaimFailureClaimed: "This chunk is already claimed."
  chunkClaimFailureRegion: "This chunk is protected."
  notClaimOwner: "You don't have a claim."
  notTrusteeOfClaim: "That person is not a trustee of this claim."
  notMemberOfClaim: "That person is not a member of this claim."
  notInsideClaim: "You are not inside a claim."
  addMemberSuccess: "Added %s to your claim."
  addTrusteeSuccess: "Added %s as a trustee of your claim."
  removeMemberSuccess: "Removed %s from your claim."
  removeTrusteeSuccess: "Removed trustee %s from your claim."
  removeMemberFailureSelf: "You cannot remove yourself from your claim."
  unknownPlayer: "Unknown player."
  claimRemoveSuccess: "Unclaimed %d chunks."
  usageSpecifyClaimName: "You must specify a claim name."
  hasNoClaim: "That player doesn't have a claim."
  claimRemoveSuccessOther: "Removed %s's claim of %d chunks."
  personAlreadyMember: "That person is already a member."
  personAlreadyTrusted: "That person is already trusted."
  memberChangeLevelSuccess: "Changed %s's level to %s."
  memberChangeLevelFailure: "%s is already level %s."