name: Claims
version: '${project.version}'
main: net.cozymc.main.ClaimsPlugin
api-version: 1.13
depend: [WorldGuard, EssentialsX]
author: [escape9179]
description: Inspired by ManaCube's claim plugin.
permissions:
  cozyclaims.*:
    description: Access all plugin capabilities and commands.
  cozyclaims.claim:
    description: Claim a chunk of land.
  cozyclaims.reload:
    description: Reload the configuration.
